# Generated by Django 4.2.1 on 2023-05-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('about', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('shop', models.CharField(max_length=100)),
            ],
        ),
    ]
