# Generated by Django 4.2.1 on 2023-05-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reste', '0002_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
