# Generated by Django 4.2.1 on 2023-05-30 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reste', '0003_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='reviews',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reste.reviews'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviews',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
