# Generated by Django 4.2.1 on 2023-05-30 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reste', '0004_blog_reviews_alter_reviews_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='reviews',
        ),
    ]
