# Generated by Django 4.2.1 on 2023-05-30 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reste', '0005_remove_blog_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='reviews',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reste.reviews'),
            preserve_default=False,
        ),
    ]
