# Generated by Django 4.2.1 on 2023-06-01 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reste', '0008_remove_reviews_reviews_blog_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
    ]
